### ISSUE TITLE
Space to exit game

### ISSUE THREAD

**Issue by RedFomoire** [bellsye/SevenMoons_Game#15]
**Describe the bug**

Code is in the game to immediately exit the game

**Version**
PGF Demo build

**To Reproduce**
1. Launch scene
2. Press Space
3. See Error

**Expected behavior**
Space should not be doing anything active outside of any new minigames

**Screenshots**
NA

**Desktop System:**
WINDOWS

**Additional context**
NA

**Comment by birdmohawk** [comment]
I went to have a look at this but couldn't find the bug. Have pressed space in all scenes and it doesn't close - will probably need testing on other computers.

**Comment by RedFomoire** [comment]
Issue resolved, was using outdated model at the time
