### ISSUE TITLE
Exiting the game

### ISSUE THREAD

**Issue by jassminne** [bellsye/SevenMoons_Game#2]
**Describe the bug**

During the playtesting, a participant suggested on adding a way to exit the game as they have to either use the task manager or ALT+F4 to exit the game. 

**Version**
Seven Moons Test Release v001-alpha

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the build found in the latest release [here](https://github.com/bellsye/SevenMoons_Game/releases/tag/v001-alpha). It is labelled Seven Moons inside the SevenMoons_v001 zip folder.
2. Once the scene is loaded.

**Expected behaviour**
Players are able to exit the game with an exit button.

**Screenshots**
None.

**Desktop System (please complete the following information):**
Windows

**Additional context**
n/a

**Comment by birdmohawk** [comment]
Have added ExitScript, which will be added to every scene so the player can exit the game.
