### ISSUE TITLE
Interaction and Dialogue UI placed inconsistently

### ISSUE THREAD

**Issue by birdmohawk** [bellsye/SevenMoons_Game#4]
**Version**
Seven Moons Test Release v001-alpha

**To Reproduce**
1. Go to Campground or Forest area.
2. Walk to interactable object/NPC. 
3. View text UI that pops up.

**Expected behavior**
UI that pops up when in range of an interactable object or NPC should be placed consistently and look good.

**Screenshots**
![image](https://user-images.githubusercontent.com/69902855/117596784-b6704380-b176-11eb-9bf1-127eb31bba21.png)

**Desktop System (please complete the following information):**
OS: Windows 10

**Additional context**
Josh suggested placing UI under the player's feet instead.

**Comment by RedFomoire** [comment]
Text placement was adjusted accordingly in all scenes. tested well
